### ISSUE TITLE
Implement recommended community standards to the project

### ISSUE THREAD

**Issue by orama254** [fossbarrow/swedish-ssn-validator#12]
Hello Team,

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/fossbarrow/global-ssn-validator/community) that would make the project contributor friendly, e.g. a code of conduct, a contributing file, an issue template and a pull request template.

Let me know if this is something you would like to implement on this project.

**Comment by PatricNox** [comment]
> Hello Team,
> 
> I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/fossbarrow/global-ssn-validator/community) that would make the project contributor friendly, e.g. a code of conduct, a contributing file, an issue template and a pull request template.
> 
> Let me know if this is something you would like to implement on this project.

Hello,


feel free to make those!  :)
