### ISSUE TITLE
It doesn't really validate it?

### ISSUE THREAD

**Issue by molteber** [fossbarrow/swedish-ssn-validator#5]
Hi guys,

Found this package when looking for a swedish ssn validator. However, it does not validate the validity of the number, only the format? You're not doing any checksum validations at all?

You should either add checksum validation too, or update the readme stating what you actually validate

**Comment by PatricNox** [comment]
Hi @molteber. 

This is something that's being worked on. Feel free to open a PR to speed up the process!

**Comment by molteber** [comment]
Awesome, looking forward to it :) Went for another package for this project, but might tune into this the next time :+1:

**Comment by Mr1BitL8r** [comment]
Hi everybody,

The missing validation of the checksum should be fixed with Pull Request #6 . :)

**Comment by PatricNox** [comment]
Thanks so much @Mr1BitL8r, greatly appreciated!

@molteber maybe could test it to see if it fits his search parameters for the perfect SSN validator package?
