### ISSUE TITLE
Issue with date validation?

### ISSUE THREAD

**Issue by Mr1BitL8r** [fossbarrow/swedish-ssn-validator#7]
Hi everybody,

Not sure if the current date validation is correct all the time, e.g. for **811228-9874** (taken from [Wikipedia)]( https://en.wikipedia.org/wiki/Personal_identity_number_(Sweden)) the validation **fails** as the array gets split into 2 and not 4 parts:

```
    if (dateArr.length !== 4) {
      //Invalid SSN format
      return false;
    }
```

**Comment by PatricNox** [comment]
Please pull and try the latest commit, it should all be good now as we've turned into a global ssn validator.
